# Generated by Django 5.2.6 on 2025-09-09 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepCAService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(help_text='Step-CA service URL (e.g., localhost:9000)', max_length=255)),
                ('ca_url', models.CharField(help_text='CA URL for certificate operations', max_length=255)),
                ('ca_fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('root_cert_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(default='unknown', max_length=50)),
                ('default_validity', models.CharField(default='1-year', max_length=20)),
                ('max_validity', models.CharField(default='5-years', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Step-CA Service',
                'verbose_name_plural': 'Step-CA Services',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(help_text='Hostname or IP address', max_length=255)),
                ('certificate_type', models.CharField(choices=[('self_signed', 'Self-Signed'), ('ca_signed', 'CA-Signed'), ('step_ca', 'Step-CA')], default='step_ca', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('key_size', models.CharField(choices=[('2048', '2048'), ('4096', '4096'), ('8192', '8192')], default='2048', max_length=10)),
                ('validity_period', models.CharField(default='1-year', max_length=20)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.CharField(default='Step-CA Service', max_length=255)),
                ('step_ca_service', models.CharField(default='localhost:9000', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Optional email for certificate notifications', max_length=254, null=True)),
                ('certificate_content', models.TextField(blank=True, help_text='PEM formatted certificate', null=True)),
                ('private_key', models.TextField(blank=True, help_text='PEM formatted private key', null=True)),
                ('certificate_chain', models.TextField(blank=True, help_text='Certificate chain if applicable', null=True)),
                ('step_ca_token', models.CharField(blank=True, max_length=500, null=True)),
                ('step_ca_fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('last_validation_check', models.DateTimeField(blank=True, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('validity_period', models.CharField(max_length=20)),
                ('step_ca_service', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['hostname'], name='certificate_hostnam_11f71d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_31e804_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['expiry_date'], name='certificate_expiry__2f5bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['created_by'], name='certificate_created_048a5b_idx'),
        ),
    ]
