# Generated by Django 5.2.6 on 2025-09-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
